package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// ChannelID is the resolver for the channelID field.
func (r *channelProbeDataResolver) ChannelID(ctx context.Context, obj *biz.ChannelProbeData) (*objects.GUID, error) {
	return &objects.GUID{
		Type: "Channel",
		ID:   obj.ChannelID,
	}, nil
}

// ChannelProbeData is the resolver for the channelProbeData field.
func (r *queryResolver) ChannelProbeData(ctx context.Context, input biz.GetChannelProbeDataInput) ([]*biz.ChannelProbeData, error) {
	return r.channelProbeService.BatchQueryChannelProbes(ctx, input)
}

// ChannelProbeData returns ChannelProbeDataResolver implementation.
func (r *Resolver) ChannelProbeData() ChannelProbeDataResolver { return &channelProbeDataResolver{r} }

type channelProbeDataResolver struct{ *Resolver }
