package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/prompt"
	"github.com/looplj/axonhub/internal/objects"
)

// CreatePrompt is the resolver for the createPrompt field.
func (r *mutationResolver) CreatePrompt(ctx context.Context, input ent.CreatePromptInput) (*ent.Prompt, error) {
	return r.promptService.CreatePrompt(ctx, input)
}

// UpdatePrompt is the resolver for the updatePrompt field.
func (r *mutationResolver) UpdatePrompt(ctx context.Context, id objects.GUID, input ent.UpdatePromptInput) (*ent.Prompt, error) {
	return r.promptService.UpdatePrompt(ctx, id.ID, &input)
}

// DeletePrompt is the resolver for the deletePrompt field.
func (r *mutationResolver) DeletePrompt(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.promptService.DeletePrompt(ctx, id.ID); err != nil {
		return false, err
	}

	return true, nil
}

// UpdatePromptStatus is the resolver for the updatePromptStatus field.
func (r *mutationResolver) UpdatePromptStatus(ctx context.Context, id objects.GUID, status prompt.Status) (bool, error) {
	_, err := r.promptService.UpdatePromptStatus(ctx, id.ID, status)
	if err != nil {
		return false, err
	}

	return true, nil
}

// BulkDeletePrompts is the resolver for the bulkDeletePrompts field.
func (r *mutationResolver) BulkDeletePrompts(ctx context.Context, ids []*objects.GUID) (bool, error) {
	promptIDs := objects.IntGuids(ids)

	if err := r.promptService.BulkDeletePrompts(ctx, promptIDs); err != nil {
		return false, err
	}

	return true, nil
}

// BulkEnablePrompts is the resolver for the bulkEnablePrompts field.
func (r *mutationResolver) BulkEnablePrompts(ctx context.Context, ids []*objects.GUID) (bool, error) {
	promptIDs := objects.IntGuids(ids)

	if err := r.promptService.BulkEnablePrompts(ctx, promptIDs); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDisablePrompts is the resolver for the bulkDisablePrompts field.
func (r *mutationResolver) BulkDisablePrompts(ctx context.Context, ids []*objects.GUID) (bool, error) {
	promptIDs := objects.IntGuids(ids)

	if err := r.promptService.BulkDisablePrompts(ctx, promptIDs); err != nil {
		return false, err
	}

	return true, nil
}
