// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channeloverridetemplate"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/objects"
)

// ChannelOverrideTemplateUpdate is the builder for updating ChannelOverrideTemplate entities.
type ChannelOverrideTemplateUpdate struct {
	config
	hooks     []Hook
	mutation  *ChannelOverrideTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChannelOverrideTemplateUpdate builder.
func (_u *ChannelOverrideTemplateUpdate) Where(ps ...predicate.ChannelOverrideTemplate) *ChannelOverrideTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelOverrideTemplateUpdate) SetUpdatedAt(v time.Time) *ChannelOverrideTemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChannelOverrideTemplateUpdate) SetDeletedAt(v int) *ChannelOverrideTemplateUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChannelOverrideTemplateUpdate) SetNillableDeletedAt(v *int) *ChannelOverrideTemplateUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ChannelOverrideTemplateUpdate) AddDeletedAt(v int) *ChannelOverrideTemplateUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelOverrideTemplateUpdate) SetName(v string) *ChannelOverrideTemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelOverrideTemplateUpdate) SetNillableName(v *string) *ChannelOverrideTemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ChannelOverrideTemplateUpdate) SetDescription(v string) *ChannelOverrideTemplateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ChannelOverrideTemplateUpdate) SetNillableDescription(v *string) *ChannelOverrideTemplateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ChannelOverrideTemplateUpdate) ClearDescription() *ChannelOverrideTemplateUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetOverrideParameters sets the "override_parameters" field.
func (_u *ChannelOverrideTemplateUpdate) SetOverrideParameters(v string) *ChannelOverrideTemplateUpdate {
	_u.mutation.SetOverrideParameters(v)
	return _u
}

// SetNillableOverrideParameters sets the "override_parameters" field if the given value is not nil.
func (_u *ChannelOverrideTemplateUpdate) SetNillableOverrideParameters(v *string) *ChannelOverrideTemplateUpdate {
	if v != nil {
		_u.SetOverrideParameters(*v)
	}
	return _u
}

// SetOverrideHeaders sets the "override_headers" field.
func (_u *ChannelOverrideTemplateUpdate) SetOverrideHeaders(v []objects.HeaderEntry) *ChannelOverrideTemplateUpdate {
	_u.mutation.SetOverrideHeaders(v)
	return _u
}

// AppendOverrideHeaders appends value to the "override_headers" field.
func (_u *ChannelOverrideTemplateUpdate) AppendOverrideHeaders(v []objects.HeaderEntry) *ChannelOverrideTemplateUpdate {
	_u.mutation.AppendOverrideHeaders(v)
	return _u
}

// SetHeaderOverrideOperations sets the "header_override_operations" field.
func (_u *ChannelOverrideTemplateUpdate) SetHeaderOverrideOperations(v []objects.OverrideOperation) *ChannelOverrideTemplateUpdate {
	_u.mutation.SetHeaderOverrideOperations(v)
	return _u
}

// AppendHeaderOverrideOperations appends value to the "header_override_operations" field.
func (_u *ChannelOverrideTemplateUpdate) AppendHeaderOverrideOperations(v []objects.OverrideOperation) *ChannelOverrideTemplateUpdate {
	_u.mutation.AppendHeaderOverrideOperations(v)
	return _u
}

// ClearHeaderOverrideOperations clears the value of the "header_override_operations" field.
func (_u *ChannelOverrideTemplateUpdate) ClearHeaderOverrideOperations() *ChannelOverrideTemplateUpdate {
	_u.mutation.ClearHeaderOverrideOperations()
	return _u
}

// SetBodyOverrideOperations sets the "body_override_operations" field.
func (_u *ChannelOverrideTemplateUpdate) SetBodyOverrideOperations(v []objects.OverrideOperation) *ChannelOverrideTemplateUpdate {
	_u.mutation.SetBodyOverrideOperations(v)
	return _u
}

// AppendBodyOverrideOperations appends value to the "body_override_operations" field.
func (_u *ChannelOverrideTemplateUpdate) AppendBodyOverrideOperations(v []objects.OverrideOperation) *ChannelOverrideTemplateUpdate {
	_u.mutation.AppendBodyOverrideOperations(v)
	return _u
}

// ClearBodyOverrideOperations clears the value of the "body_override_operations" field.
func (_u *ChannelOverrideTemplateUpdate) ClearBodyOverrideOperations() *ChannelOverrideTemplateUpdate {
	_u.mutation.ClearBodyOverrideOperations()
	return _u
}

// Mutation returns the ChannelOverrideTemplateMutation object of the builder.
func (_u *ChannelOverrideTemplateUpdate) Mutation() *ChannelOverrideTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelOverrideTemplateUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelOverrideTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelOverrideTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelOverrideTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelOverrideTemplateUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channeloverridetemplate.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channeloverridetemplate.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channeloverridetemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelOverrideTemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := channeloverridetemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChannelOverrideTemplate.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelOverrideTemplateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelOverrideTemplateUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelOverrideTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channeloverridetemplate.Table, channeloverridetemplate.Columns, sqlgraph.NewFieldSpec(channeloverridetemplate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channeloverridetemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(channeloverridetemplate.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(channeloverridetemplate.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channeloverridetemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(channeloverridetemplate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(channeloverridetemplate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OverrideParameters(); ok {
		_spec.SetField(channeloverridetemplate.FieldOverrideParameters, field.TypeString, value)
	}
	if value, ok := _u.mutation.OverrideHeaders(); ok {
		_spec.SetField(channeloverridetemplate.FieldOverrideHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOverrideHeaders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channeloverridetemplate.FieldOverrideHeaders, value)
		})
	}
	if value, ok := _u.mutation.HeaderOverrideOperations(); ok {
		_spec.SetField(channeloverridetemplate.FieldHeaderOverrideOperations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHeaderOverrideOperations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channeloverridetemplate.FieldHeaderOverrideOperations, value)
		})
	}
	if _u.mutation.HeaderOverrideOperationsCleared() {
		_spec.ClearField(channeloverridetemplate.FieldHeaderOverrideOperations, field.TypeJSON)
	}
	if value, ok := _u.mutation.BodyOverrideOperations(); ok {
		_spec.SetField(channeloverridetemplate.FieldBodyOverrideOperations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBodyOverrideOperations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channeloverridetemplate.FieldBodyOverrideOperations, value)
		})
	}
	if _u.mutation.BodyOverrideOperationsCleared() {
		_spec.ClearField(channeloverridetemplate.FieldBodyOverrideOperations, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channeloverridetemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelOverrideTemplateUpdateOne is the builder for updating a single ChannelOverrideTemplate entity.
type ChannelOverrideTemplateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChannelOverrideTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelOverrideTemplateUpdateOne) SetUpdatedAt(v time.Time) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChannelOverrideTemplateUpdateOne) SetDeletedAt(v int) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChannelOverrideTemplateUpdateOne) SetNillableDeletedAt(v *int) *ChannelOverrideTemplateUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ChannelOverrideTemplateUpdateOne) AddDeletedAt(v int) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelOverrideTemplateUpdateOne) SetName(v string) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelOverrideTemplateUpdateOne) SetNillableName(v *string) *ChannelOverrideTemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ChannelOverrideTemplateUpdateOne) SetDescription(v string) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ChannelOverrideTemplateUpdateOne) SetNillableDescription(v *string) *ChannelOverrideTemplateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ChannelOverrideTemplateUpdateOne) ClearDescription() *ChannelOverrideTemplateUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetOverrideParameters sets the "override_parameters" field.
func (_u *ChannelOverrideTemplateUpdateOne) SetOverrideParameters(v string) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.SetOverrideParameters(v)
	return _u
}

// SetNillableOverrideParameters sets the "override_parameters" field if the given value is not nil.
func (_u *ChannelOverrideTemplateUpdateOne) SetNillableOverrideParameters(v *string) *ChannelOverrideTemplateUpdateOne {
	if v != nil {
		_u.SetOverrideParameters(*v)
	}
	return _u
}

// SetOverrideHeaders sets the "override_headers" field.
func (_u *ChannelOverrideTemplateUpdateOne) SetOverrideHeaders(v []objects.HeaderEntry) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.SetOverrideHeaders(v)
	return _u
}

// AppendOverrideHeaders appends value to the "override_headers" field.
func (_u *ChannelOverrideTemplateUpdateOne) AppendOverrideHeaders(v []objects.HeaderEntry) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.AppendOverrideHeaders(v)
	return _u
}

// SetHeaderOverrideOperations sets the "header_override_operations" field.
func (_u *ChannelOverrideTemplateUpdateOne) SetHeaderOverrideOperations(v []objects.OverrideOperation) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.SetHeaderOverrideOperations(v)
	return _u
}

// AppendHeaderOverrideOperations appends value to the "header_override_operations" field.
func (_u *ChannelOverrideTemplateUpdateOne) AppendHeaderOverrideOperations(v []objects.OverrideOperation) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.AppendHeaderOverrideOperations(v)
	return _u
}

// ClearHeaderOverrideOperations clears the value of the "header_override_operations" field.
func (_u *ChannelOverrideTemplateUpdateOne) ClearHeaderOverrideOperations() *ChannelOverrideTemplateUpdateOne {
	_u.mutation.ClearHeaderOverrideOperations()
	return _u
}

// SetBodyOverrideOperations sets the "body_override_operations" field.
func (_u *ChannelOverrideTemplateUpdateOne) SetBodyOverrideOperations(v []objects.OverrideOperation) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.SetBodyOverrideOperations(v)
	return _u
}

// AppendBodyOverrideOperations appends value to the "body_override_operations" field.
func (_u *ChannelOverrideTemplateUpdateOne) AppendBodyOverrideOperations(v []objects.OverrideOperation) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.AppendBodyOverrideOperations(v)
	return _u
}

// ClearBodyOverrideOperations clears the value of the "body_override_operations" field.
func (_u *ChannelOverrideTemplateUpdateOne) ClearBodyOverrideOperations() *ChannelOverrideTemplateUpdateOne {
	_u.mutation.ClearBodyOverrideOperations()
	return _u
}

// Mutation returns the ChannelOverrideTemplateMutation object of the builder.
func (_u *ChannelOverrideTemplateUpdateOne) Mutation() *ChannelOverrideTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChannelOverrideTemplateUpdate builder.
func (_u *ChannelOverrideTemplateUpdateOne) Where(ps ...predicate.ChannelOverrideTemplate) *ChannelOverrideTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelOverrideTemplateUpdateOne) Select(field string, fields ...string) *ChannelOverrideTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelOverrideTemplate entity.
func (_u *ChannelOverrideTemplateUpdateOne) Save(ctx context.Context) (*ChannelOverrideTemplate, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelOverrideTemplateUpdateOne) SaveX(ctx context.Context) *ChannelOverrideTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelOverrideTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelOverrideTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelOverrideTemplateUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channeloverridetemplate.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channeloverridetemplate.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channeloverridetemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelOverrideTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := channeloverridetemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChannelOverrideTemplate.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelOverrideTemplateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelOverrideTemplateUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelOverrideTemplateUpdateOne) sqlSave(ctx context.Context) (_node *ChannelOverrideTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channeloverridetemplate.Table, channeloverridetemplate.Columns, sqlgraph.NewFieldSpec(channeloverridetemplate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelOverrideTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channeloverridetemplate.FieldID)
		for _, f := range fields {
			if !channeloverridetemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channeloverridetemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channeloverridetemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(channeloverridetemplate.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(channeloverridetemplate.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channeloverridetemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(channeloverridetemplate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(channeloverridetemplate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OverrideParameters(); ok {
		_spec.SetField(channeloverridetemplate.FieldOverrideParameters, field.TypeString, value)
	}
	if value, ok := _u.mutation.OverrideHeaders(); ok {
		_spec.SetField(channeloverridetemplate.FieldOverrideHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOverrideHeaders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channeloverridetemplate.FieldOverrideHeaders, value)
		})
	}
	if value, ok := _u.mutation.HeaderOverrideOperations(); ok {
		_spec.SetField(channeloverridetemplate.FieldHeaderOverrideOperations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHeaderOverrideOperations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channeloverridetemplate.FieldHeaderOverrideOperations, value)
		})
	}
	if _u.mutation.HeaderOverrideOperationsCleared() {
		_spec.ClearField(channeloverridetemplate.FieldHeaderOverrideOperations, field.TypeJSON)
	}
	if value, ok := _u.mutation.BodyOverrideOperations(); ok {
		_spec.SetField(channeloverridetemplate.FieldBodyOverrideOperations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBodyOverrideOperations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channeloverridetemplate.FieldBodyOverrideOperations, value)
		})
	}
	if _u.mutation.BodyOverrideOperationsCleared() {
		_spec.ClearField(channeloverridetemplate.FieldBodyOverrideOperations, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ChannelOverrideTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channeloverridetemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
