// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channelmodelprice"
	"github.com/looplj/axonhub/internal/ent/channelmodelpriceversion"
	"github.com/looplj/axonhub/internal/objects"
)

// ChannelModelPriceVersionCreate is the builder for creating a ChannelModelPriceVersion entity.
type ChannelModelPriceVersionCreate struct {
	config
	mutation *ChannelModelPriceVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelModelPriceVersionCreate) SetCreatedAt(v time.Time) *ChannelModelPriceVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelModelPriceVersionCreate) SetNillableCreatedAt(v *time.Time) *ChannelModelPriceVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelModelPriceVersionCreate) SetUpdatedAt(v time.Time) *ChannelModelPriceVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelModelPriceVersionCreate) SetNillableUpdatedAt(v *time.Time) *ChannelModelPriceVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ChannelModelPriceVersionCreate) SetChannelID(v int) *ChannelModelPriceVersionCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *ChannelModelPriceVersionCreate) SetModelID(v string) *ChannelModelPriceVersionCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetChannelModelPriceID sets the "channel_model_price_id" field.
func (_c *ChannelModelPriceVersionCreate) SetChannelModelPriceID(v int) *ChannelModelPriceVersionCreate {
	_c.mutation.SetChannelModelPriceID(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *ChannelModelPriceVersionCreate) SetPrice(v objects.ModelPrice) *ChannelModelPriceVersionCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChannelModelPriceVersionCreate) SetStatus(v channelmodelpriceversion.Status) *ChannelModelPriceVersionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetEffectiveStartAt sets the "effective_start_at" field.
func (_c *ChannelModelPriceVersionCreate) SetEffectiveStartAt(v time.Time) *ChannelModelPriceVersionCreate {
	_c.mutation.SetEffectiveStartAt(v)
	return _c
}

// SetEffectiveEndAt sets the "effective_end_at" field.
func (_c *ChannelModelPriceVersionCreate) SetEffectiveEndAt(v time.Time) *ChannelModelPriceVersionCreate {
	_c.mutation.SetEffectiveEndAt(v)
	return _c
}

// SetNillableEffectiveEndAt sets the "effective_end_at" field if the given value is not nil.
func (_c *ChannelModelPriceVersionCreate) SetNillableEffectiveEndAt(v *time.Time) *ChannelModelPriceVersionCreate {
	if v != nil {
		_c.SetEffectiveEndAt(*v)
	}
	return _c
}

// SetReferenceID sets the "reference_id" field.
func (_c *ChannelModelPriceVersionCreate) SetReferenceID(v string) *ChannelModelPriceVersionCreate {
	_c.mutation.SetReferenceID(v)
	return _c
}

// SetChannelModelPrice sets the "channel_model_price" edge to the ChannelModelPrice entity.
func (_c *ChannelModelPriceVersionCreate) SetChannelModelPrice(v *ChannelModelPrice) *ChannelModelPriceVersionCreate {
	return _c.SetChannelModelPriceID(v.ID)
}

// Mutation returns the ChannelModelPriceVersionMutation object of the builder.
func (_c *ChannelModelPriceVersionCreate) Mutation() *ChannelModelPriceVersionMutation {
	return _c.mutation
}

// Save creates the ChannelModelPriceVersion in the database.
func (_c *ChannelModelPriceVersionCreate) Save(ctx context.Context) (*ChannelModelPriceVersion, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelModelPriceVersionCreate) SaveX(ctx context.Context) *ChannelModelPriceVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelModelPriceVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelModelPriceVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelModelPriceVersionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if channelmodelpriceversion.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelmodelpriceversion.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := channelmodelpriceversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if channelmodelpriceversion.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelmodelpriceversion.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelmodelpriceversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelModelPriceVersionCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ChannelModelPriceVersion.channel_id"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "ChannelModelPriceVersion.model_id"`)}
	}
	if _, ok := _c.mutation.ChannelModelPriceID(); !ok {
		return &ValidationError{Name: "channel_model_price_id", err: errors.New(`ent: missing required field "ChannelModelPriceVersion.channel_model_price_id"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ChannelModelPriceVersion.price"`)}
	}
	if v, ok := _c.mutation.Price(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "ChannelModelPriceVersion.price": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChannelModelPriceVersion.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := channelmodelpriceversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelModelPriceVersion.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EffectiveStartAt(); !ok {
		return &ValidationError{Name: "effective_start_at", err: errors.New(`ent: missing required field "ChannelModelPriceVersion.effective_start_at"`)}
	}
	if _, ok := _c.mutation.ReferenceID(); !ok {
		return &ValidationError{Name: "reference_id", err: errors.New(`ent: missing required field "ChannelModelPriceVersion.reference_id"`)}
	}
	if len(_c.mutation.ChannelModelPriceIDs()) == 0 {
		return &ValidationError{Name: "channel_model_price", err: errors.New(`ent: missing required edge "ChannelModelPriceVersion.channel_model_price"`)}
	}
	return nil
}

func (_c *ChannelModelPriceVersionCreate) sqlSave(ctx context.Context) (*ChannelModelPriceVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelModelPriceVersionCreate) createSpec() (*ChannelModelPriceVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelModelPriceVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelmodelpriceversion.Table, sqlgraph.NewFieldSpec(channelmodelpriceversion.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelmodelpriceversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelmodelpriceversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(channelmodelpriceversion.FieldChannelID, field.TypeInt, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(channelmodelpriceversion.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(channelmodelpriceversion.FieldPrice, field.TypeJSON, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(channelmodelpriceversion.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.EffectiveStartAt(); ok {
		_spec.SetField(channelmodelpriceversion.FieldEffectiveStartAt, field.TypeTime, value)
		_node.EffectiveStartAt = value
	}
	if value, ok := _c.mutation.EffectiveEndAt(); ok {
		_spec.SetField(channelmodelpriceversion.FieldEffectiveEndAt, field.TypeTime, value)
		_node.EffectiveEndAt = &value
	}
	if value, ok := _c.mutation.ReferenceID(); ok {
		_spec.SetField(channelmodelpriceversion.FieldReferenceID, field.TypeString, value)
		_node.ReferenceID = value
	}
	if nodes := _c.mutation.ChannelModelPriceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmodelpriceversion.ChannelModelPriceTable,
			Columns: []string{channelmodelpriceversion.ChannelModelPriceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmodelprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelModelPriceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelModelPriceVersion.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelModelPriceVersionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelModelPriceVersionCreate) OnConflict(opts ...sql.ConflictOption) *ChannelModelPriceVersionUpsertOne {
	_c.conflict = opts
	return &ChannelModelPriceVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelModelPriceVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelModelPriceVersionCreate) OnConflictColumns(columns ...string) *ChannelModelPriceVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelModelPriceVersionUpsertOne{
		create: _c,
	}
}

type (
	// ChannelModelPriceVersionUpsertOne is the builder for "upsert"-ing
	//  one ChannelModelPriceVersion node.
	ChannelModelPriceVersionUpsertOne struct {
		create *ChannelModelPriceVersionCreate
	}

	// ChannelModelPriceVersionUpsert is the "OnConflict" setter.
	ChannelModelPriceVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelModelPriceVersionUpsert) SetUpdatedAt(v time.Time) *ChannelModelPriceVersionUpsert {
	u.Set(channelmodelpriceversion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelModelPriceVersionUpsert) UpdateUpdatedAt() *ChannelModelPriceVersionUpsert {
	u.SetExcluded(channelmodelpriceversion.FieldUpdatedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *ChannelModelPriceVersionUpsert) SetStatus(v channelmodelpriceversion.Status) *ChannelModelPriceVersionUpsert {
	u.Set(channelmodelpriceversion.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelModelPriceVersionUpsert) UpdateStatus() *ChannelModelPriceVersionUpsert {
	u.SetExcluded(channelmodelpriceversion.FieldStatus)
	return u
}

// SetEffectiveEndAt sets the "effective_end_at" field.
func (u *ChannelModelPriceVersionUpsert) SetEffectiveEndAt(v time.Time) *ChannelModelPriceVersionUpsert {
	u.Set(channelmodelpriceversion.FieldEffectiveEndAt, v)
	return u
}

// UpdateEffectiveEndAt sets the "effective_end_at" field to the value that was provided on create.
func (u *ChannelModelPriceVersionUpsert) UpdateEffectiveEndAt() *ChannelModelPriceVersionUpsert {
	u.SetExcluded(channelmodelpriceversion.FieldEffectiveEndAt)
	return u
}

// ClearEffectiveEndAt clears the value of the "effective_end_at" field.
func (u *ChannelModelPriceVersionUpsert) ClearEffectiveEndAt() *ChannelModelPriceVersionUpsert {
	u.SetNull(channelmodelpriceversion.FieldEffectiveEndAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelModelPriceVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelModelPriceVersionUpsertOne) UpdateNewValues() *ChannelModelPriceVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelmodelpriceversion.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ChannelID(); exists {
			s.SetIgnore(channelmodelpriceversion.FieldChannelID)
		}
		if _, exists := u.create.mutation.ModelID(); exists {
			s.SetIgnore(channelmodelpriceversion.FieldModelID)
		}
		if _, exists := u.create.mutation.ChannelModelPriceID(); exists {
			s.SetIgnore(channelmodelpriceversion.FieldChannelModelPriceID)
		}
		if _, exists := u.create.mutation.Price(); exists {
			s.SetIgnore(channelmodelpriceversion.FieldPrice)
		}
		if _, exists := u.create.mutation.EffectiveStartAt(); exists {
			s.SetIgnore(channelmodelpriceversion.FieldEffectiveStartAt)
		}
		if _, exists := u.create.mutation.ReferenceID(); exists {
			s.SetIgnore(channelmodelpriceversion.FieldReferenceID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelModelPriceVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelModelPriceVersionUpsertOne) Ignore() *ChannelModelPriceVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelModelPriceVersionUpsertOne) DoNothing() *ChannelModelPriceVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelModelPriceVersionCreate.OnConflict
// documentation for more info.
func (u *ChannelModelPriceVersionUpsertOne) Update(set func(*ChannelModelPriceVersionUpsert)) *ChannelModelPriceVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelModelPriceVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelModelPriceVersionUpsertOne) SetUpdatedAt(v time.Time) *ChannelModelPriceVersionUpsertOne {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelModelPriceVersionUpsertOne) UpdateUpdatedAt() *ChannelModelPriceVersionUpsertOne {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelModelPriceVersionUpsertOne) SetStatus(v channelmodelpriceversion.Status) *ChannelModelPriceVersionUpsertOne {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelModelPriceVersionUpsertOne) UpdateStatus() *ChannelModelPriceVersionUpsertOne {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetEffectiveEndAt sets the "effective_end_at" field.
func (u *ChannelModelPriceVersionUpsertOne) SetEffectiveEndAt(v time.Time) *ChannelModelPriceVersionUpsertOne {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.SetEffectiveEndAt(v)
	})
}

// UpdateEffectiveEndAt sets the "effective_end_at" field to the value that was provided on create.
func (u *ChannelModelPriceVersionUpsertOne) UpdateEffectiveEndAt() *ChannelModelPriceVersionUpsertOne {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.UpdateEffectiveEndAt()
	})
}

// ClearEffectiveEndAt clears the value of the "effective_end_at" field.
func (u *ChannelModelPriceVersionUpsertOne) ClearEffectiveEndAt() *ChannelModelPriceVersionUpsertOne {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.ClearEffectiveEndAt()
	})
}

// Exec executes the query.
func (u *ChannelModelPriceVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelModelPriceVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelModelPriceVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelModelPriceVersionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelModelPriceVersionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelModelPriceVersionCreateBulk is the builder for creating many ChannelModelPriceVersion entities in bulk.
type ChannelModelPriceVersionCreateBulk struct {
	config
	err      error
	builders []*ChannelModelPriceVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelModelPriceVersion entities in the database.
func (_c *ChannelModelPriceVersionCreateBulk) Save(ctx context.Context) ([]*ChannelModelPriceVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelModelPriceVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelModelPriceVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelModelPriceVersionCreateBulk) SaveX(ctx context.Context) []*ChannelModelPriceVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelModelPriceVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelModelPriceVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelModelPriceVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelModelPriceVersionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelModelPriceVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelModelPriceVersionUpsertBulk {
	_c.conflict = opts
	return &ChannelModelPriceVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelModelPriceVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelModelPriceVersionCreateBulk) OnConflictColumns(columns ...string) *ChannelModelPriceVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelModelPriceVersionUpsertBulk{
		create: _c,
	}
}

// ChannelModelPriceVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelModelPriceVersion nodes.
type ChannelModelPriceVersionUpsertBulk struct {
	create *ChannelModelPriceVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelModelPriceVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelModelPriceVersionUpsertBulk) UpdateNewValues() *ChannelModelPriceVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelmodelpriceversion.FieldCreatedAt)
			}
			if _, exists := b.mutation.ChannelID(); exists {
				s.SetIgnore(channelmodelpriceversion.FieldChannelID)
			}
			if _, exists := b.mutation.ModelID(); exists {
				s.SetIgnore(channelmodelpriceversion.FieldModelID)
			}
			if _, exists := b.mutation.ChannelModelPriceID(); exists {
				s.SetIgnore(channelmodelpriceversion.FieldChannelModelPriceID)
			}
			if _, exists := b.mutation.Price(); exists {
				s.SetIgnore(channelmodelpriceversion.FieldPrice)
			}
			if _, exists := b.mutation.EffectiveStartAt(); exists {
				s.SetIgnore(channelmodelpriceversion.FieldEffectiveStartAt)
			}
			if _, exists := b.mutation.ReferenceID(); exists {
				s.SetIgnore(channelmodelpriceversion.FieldReferenceID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelModelPriceVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelModelPriceVersionUpsertBulk) Ignore() *ChannelModelPriceVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelModelPriceVersionUpsertBulk) DoNothing() *ChannelModelPriceVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelModelPriceVersionCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelModelPriceVersionUpsertBulk) Update(set func(*ChannelModelPriceVersionUpsert)) *ChannelModelPriceVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelModelPriceVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelModelPriceVersionUpsertBulk) SetUpdatedAt(v time.Time) *ChannelModelPriceVersionUpsertBulk {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelModelPriceVersionUpsertBulk) UpdateUpdatedAt() *ChannelModelPriceVersionUpsertBulk {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelModelPriceVersionUpsertBulk) SetStatus(v channelmodelpriceversion.Status) *ChannelModelPriceVersionUpsertBulk {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelModelPriceVersionUpsertBulk) UpdateStatus() *ChannelModelPriceVersionUpsertBulk {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetEffectiveEndAt sets the "effective_end_at" field.
func (u *ChannelModelPriceVersionUpsertBulk) SetEffectiveEndAt(v time.Time) *ChannelModelPriceVersionUpsertBulk {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.SetEffectiveEndAt(v)
	})
}

// UpdateEffectiveEndAt sets the "effective_end_at" field to the value that was provided on create.
func (u *ChannelModelPriceVersionUpsertBulk) UpdateEffectiveEndAt() *ChannelModelPriceVersionUpsertBulk {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.UpdateEffectiveEndAt()
	})
}

// ClearEffectiveEndAt clears the value of the "effective_end_at" field.
func (u *ChannelModelPriceVersionUpsertBulk) ClearEffectiveEndAt() *ChannelModelPriceVersionUpsertBulk {
	return u.Update(func(s *ChannelModelPriceVersionUpsert) {
		s.ClearEffectiveEndAt()
	})
}

// Exec executes the query.
func (u *ChannelModelPriceVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelModelPriceVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelModelPriceVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelModelPriceVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
