// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/model"
	"github.com/looplj/axonhub/internal/objects"
)

// ModelCreate is the builder for creating a Model entity.
type ModelCreate struct {
	config
	mutation *ModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelCreate) SetCreatedAt(v time.Time) *ModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelCreate) SetNillableCreatedAt(v *time.Time) *ModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelCreate) SetUpdatedAt(v time.Time) *ModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelCreate) SetNillableUpdatedAt(v *time.Time) *ModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ModelCreate) SetDeletedAt(v int) *ModelCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ModelCreate) SetNillableDeletedAt(v *int) *ModelCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeveloper sets the "developer" field.
func (_c *ModelCreate) SetDeveloper(v string) *ModelCreate {
	_c.mutation.SetDeveloper(v)
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *ModelCreate) SetModelID(v string) *ModelCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ModelCreate) SetType(v model.Type) *ModelCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ModelCreate) SetNillableType(v *model.Type) *ModelCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ModelCreate) SetName(v string) *ModelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIcon sets the "icon" field.
func (_c *ModelCreate) SetIcon(v string) *ModelCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetGroup sets the "group" field.
func (_c *ModelCreate) SetGroup(v string) *ModelCreate {
	_c.mutation.SetGroup(v)
	return _c
}

// SetModelCard sets the "model_card" field.
func (_c *ModelCreate) SetModelCard(v *objects.ModelCard) *ModelCreate {
	_c.mutation.SetModelCard(v)
	return _c
}

// SetSettings sets the "settings" field.
func (_c *ModelCreate) SetSettings(v *objects.ModelSettings) *ModelCreate {
	_c.mutation.SetSettings(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ModelCreate) SetStatus(v model.Status) *ModelCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ModelCreate) SetNillableStatus(v *model.Status) *ModelCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ModelCreate) SetRemark(v string) *ModelCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ModelCreate) SetNillableRemark(v *string) *ModelCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// Mutation returns the ModelMutation object of the builder.
func (_c *ModelCreate) Mutation() *ModelMutation {
	return _c.mutation
}

// Save creates the Model in the database.
func (_c *ModelCreate) Save(ctx context.Context) (*Model, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelCreate) SaveX(ctx context.Context) *Model {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if model.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized model.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := model.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if model.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized model.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := model.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := model.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := model.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := model.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Model.deleted_at"`)}
	}
	if _, ok := _c.mutation.Developer(); !ok {
		return &ValidationError{Name: "developer", err: errors.New(`ent: missing required field "Model.developer"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "Model.model_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Model.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := model.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Model.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Model.name"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "Model.icon"`)}
	}
	if _, ok := _c.mutation.Group(); !ok {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required field "Model.group"`)}
	}
	if _, ok := _c.mutation.ModelCard(); !ok {
		return &ValidationError{Name: "model_card", err: errors.New(`ent: missing required field "Model.model_card"`)}
	}
	if _, ok := _c.mutation.Settings(); !ok {
		return &ValidationError{Name: "settings", err: errors.New(`ent: missing required field "Model.settings"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Model.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := model.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Model.status": %w`, err)}
		}
	}
	return nil
}

func (_c *ModelCreate) sqlSave(ctx context.Context) (*Model, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelCreate) createSpec() (*Model, *sqlgraph.CreateSpec) {
	var (
		_node = &Model{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(model.Table, sqlgraph.NewFieldSpec(model.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(model.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(model.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(model.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Developer(); ok {
		_spec.SetField(model.FieldDeveloper, field.TypeString, value)
		_node.Developer = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(model.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(model.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(model.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(model.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.Group(); ok {
		_spec.SetField(model.FieldGroup, field.TypeString, value)
		_node.Group = value
	}
	if value, ok := _c.mutation.ModelCard(); ok {
		_spec.SetField(model.FieldModelCard, field.TypeJSON, value)
		_node.ModelCard = value
	}
	if value, ok := _c.mutation.Settings(); ok {
		_spec.SetField(model.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(model.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(model.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Model.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCreate) OnConflict(opts ...sql.ConflictOption) *ModelUpsertOne {
	_c.conflict = opts
	return &ModelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Model.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCreate) OnConflictColumns(columns ...string) *ModelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelUpsertOne{
		create: _c,
	}
}

type (
	// ModelUpsertOne is the builder for "upsert"-ing
	//  one Model node.
	ModelUpsertOne struct {
		create *ModelCreate
	}

	// ModelUpsert is the "OnConflict" setter.
	ModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelUpsert) SetUpdatedAt(v time.Time) *ModelUpsert {
	u.Set(model.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelUpsert) UpdateUpdatedAt() *ModelUpsert {
	u.SetExcluded(model.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelUpsert) SetDeletedAt(v int) *ModelUpsert {
	u.Set(model.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelUpsert) UpdateDeletedAt() *ModelUpsert {
	u.SetExcluded(model.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelUpsert) AddDeletedAt(v int) *ModelUpsert {
	u.Add(model.FieldDeletedAt, v)
	return u
}

// SetDeveloper sets the "developer" field.
func (u *ModelUpsert) SetDeveloper(v string) *ModelUpsert {
	u.Set(model.FieldDeveloper, v)
	return u
}

// UpdateDeveloper sets the "developer" field to the value that was provided on create.
func (u *ModelUpsert) UpdateDeveloper() *ModelUpsert {
	u.SetExcluded(model.FieldDeveloper)
	return u
}

// SetModelID sets the "model_id" field.
func (u *ModelUpsert) SetModelID(v string) *ModelUpsert {
	u.Set(model.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *ModelUpsert) UpdateModelID() *ModelUpsert {
	u.SetExcluded(model.FieldModelID)
	return u
}

// SetType sets the "type" field.
func (u *ModelUpsert) SetType(v model.Type) *ModelUpsert {
	u.Set(model.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ModelUpsert) UpdateType() *ModelUpsert {
	u.SetExcluded(model.FieldType)
	return u
}

// SetName sets the "name" field.
func (u *ModelUpsert) SetName(v string) *ModelUpsert {
	u.Set(model.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelUpsert) UpdateName() *ModelUpsert {
	u.SetExcluded(model.FieldName)
	return u
}

// SetIcon sets the "icon" field.
func (u *ModelUpsert) SetIcon(v string) *ModelUpsert {
	u.Set(model.FieldIcon, v)
	return u
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ModelUpsert) UpdateIcon() *ModelUpsert {
	u.SetExcluded(model.FieldIcon)
	return u
}

// SetGroup sets the "group" field.
func (u *ModelUpsert) SetGroup(v string) *ModelUpsert {
	u.Set(model.FieldGroup, v)
	return u
}

// UpdateGroup sets the "group" field to the value that was provided on create.
func (u *ModelUpsert) UpdateGroup() *ModelUpsert {
	u.SetExcluded(model.FieldGroup)
	return u
}

// SetModelCard sets the "model_card" field.
func (u *ModelUpsert) SetModelCard(v *objects.ModelCard) *ModelUpsert {
	u.Set(model.FieldModelCard, v)
	return u
}

// UpdateModelCard sets the "model_card" field to the value that was provided on create.
func (u *ModelUpsert) UpdateModelCard() *ModelUpsert {
	u.SetExcluded(model.FieldModelCard)
	return u
}

// SetSettings sets the "settings" field.
func (u *ModelUpsert) SetSettings(v *objects.ModelSettings) *ModelUpsert {
	u.Set(model.FieldSettings, v)
	return u
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *ModelUpsert) UpdateSettings() *ModelUpsert {
	u.SetExcluded(model.FieldSettings)
	return u
}

// SetStatus sets the "status" field.
func (u *ModelUpsert) SetStatus(v model.Status) *ModelUpsert {
	u.Set(model.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelUpsert) UpdateStatus() *ModelUpsert {
	u.SetExcluded(model.FieldStatus)
	return u
}

// SetRemark sets the "remark" field.
func (u *ModelUpsert) SetRemark(v string) *ModelUpsert {
	u.Set(model.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelUpsert) UpdateRemark() *ModelUpsert {
	u.SetExcluded(model.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelUpsert) ClearRemark() *ModelUpsert {
	u.SetNull(model.FieldRemark)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Model.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelUpsertOne) UpdateNewValues() *ModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(model.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Model.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelUpsertOne) Ignore() *ModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelUpsertOne) DoNothing() *ModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCreate.OnConflict
// documentation for more info.
func (u *ModelUpsertOne) Update(set func(*ModelUpsert)) *ModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelUpsertOne) SetUpdatedAt(v time.Time) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateUpdatedAt() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelUpsertOne) SetDeletedAt(v int) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelUpsertOne) AddDeletedAt(v int) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateDeletedAt() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetDeveloper sets the "developer" field.
func (u *ModelUpsertOne) SetDeveloper(v string) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetDeveloper(v)
	})
}

// UpdateDeveloper sets the "developer" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateDeveloper() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateDeveloper()
	})
}

// SetModelID sets the "model_id" field.
func (u *ModelUpsertOne) SetModelID(v string) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateModelID() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateModelID()
	})
}

// SetType sets the "type" field.
func (u *ModelUpsertOne) SetType(v model.Type) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateType() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateType()
	})
}

// SetName sets the "name" field.
func (u *ModelUpsertOne) SetName(v string) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateName() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateName()
	})
}

// SetIcon sets the "icon" field.
func (u *ModelUpsertOne) SetIcon(v string) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateIcon() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateIcon()
	})
}

// SetGroup sets the "group" field.
func (u *ModelUpsertOne) SetGroup(v string) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetGroup(v)
	})
}

// UpdateGroup sets the "group" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateGroup() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateGroup()
	})
}

// SetModelCard sets the "model_card" field.
func (u *ModelUpsertOne) SetModelCard(v *objects.ModelCard) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetModelCard(v)
	})
}

// UpdateModelCard sets the "model_card" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateModelCard() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateModelCard()
	})
}

// SetSettings sets the "settings" field.
func (u *ModelUpsertOne) SetSettings(v *objects.ModelSettings) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateSettings() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateSettings()
	})
}

// SetStatus sets the "status" field.
func (u *ModelUpsertOne) SetStatus(v model.Status) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateStatus() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateStatus()
	})
}

// SetRemark sets the "remark" field.
func (u *ModelUpsertOne) SetRemark(v string) *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelUpsertOne) UpdateRemark() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelUpsertOne) ClearRemark() *ModelUpsertOne {
	return u.Update(func(s *ModelUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *ModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelCreateBulk is the builder for creating many Model entities in bulk.
type ModelCreateBulk struct {
	config
	err      error
	builders []*ModelCreate
	conflict []sql.ConflictOption
}

// Save creates the Model entities in the database.
func (_c *ModelCreateBulk) Save(ctx context.Context) ([]*Model, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Model, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelCreateBulk) SaveX(ctx context.Context) []*Model {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Model.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelUpsertBulk {
	_c.conflict = opts
	return &ModelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Model.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCreateBulk) OnConflictColumns(columns ...string) *ModelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelUpsertBulk{
		create: _c,
	}
}

// ModelUpsertBulk is the builder for "upsert"-ing
// a bulk of Model nodes.
type ModelUpsertBulk struct {
	create *ModelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Model.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelUpsertBulk) UpdateNewValues() *ModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(model.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Model.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelUpsertBulk) Ignore() *ModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelUpsertBulk) DoNothing() *ModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCreateBulk.OnConflict
// documentation for more info.
func (u *ModelUpsertBulk) Update(set func(*ModelUpsert)) *ModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelUpsertBulk) SetUpdatedAt(v time.Time) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateUpdatedAt() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelUpsertBulk) SetDeletedAt(v int) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelUpsertBulk) AddDeletedAt(v int) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateDeletedAt() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetDeveloper sets the "developer" field.
func (u *ModelUpsertBulk) SetDeveloper(v string) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetDeveloper(v)
	})
}

// UpdateDeveloper sets the "developer" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateDeveloper() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateDeveloper()
	})
}

// SetModelID sets the "model_id" field.
func (u *ModelUpsertBulk) SetModelID(v string) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateModelID() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateModelID()
	})
}

// SetType sets the "type" field.
func (u *ModelUpsertBulk) SetType(v model.Type) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateType() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateType()
	})
}

// SetName sets the "name" field.
func (u *ModelUpsertBulk) SetName(v string) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateName() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateName()
	})
}

// SetIcon sets the "icon" field.
func (u *ModelUpsertBulk) SetIcon(v string) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateIcon() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateIcon()
	})
}

// SetGroup sets the "group" field.
func (u *ModelUpsertBulk) SetGroup(v string) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetGroup(v)
	})
}

// UpdateGroup sets the "group" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateGroup() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateGroup()
	})
}

// SetModelCard sets the "model_card" field.
func (u *ModelUpsertBulk) SetModelCard(v *objects.ModelCard) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetModelCard(v)
	})
}

// UpdateModelCard sets the "model_card" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateModelCard() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateModelCard()
	})
}

// SetSettings sets the "settings" field.
func (u *ModelUpsertBulk) SetSettings(v *objects.ModelSettings) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateSettings() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateSettings()
	})
}

// SetStatus sets the "status" field.
func (u *ModelUpsertBulk) SetStatus(v model.Status) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateStatus() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateStatus()
	})
}

// SetRemark sets the "remark" field.
func (u *ModelUpsertBulk) SetRemark(v string) *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelUpsertBulk) UpdateRemark() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelUpsertBulk) ClearRemark() *ModelUpsertBulk {
	return u.Update(func(s *ModelUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *ModelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
