// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/promptprotectionrule"
	"github.com/looplj/axonhub/internal/objects"
)

// PromptProtectionRuleCreate is the builder for creating a PromptProtectionRule entity.
type PromptProtectionRuleCreate struct {
	config
	mutation *PromptProtectionRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromptProtectionRuleCreate) SetCreatedAt(v time.Time) *PromptProtectionRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromptProtectionRuleCreate) SetNillableCreatedAt(v *time.Time) *PromptProtectionRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromptProtectionRuleCreate) SetUpdatedAt(v time.Time) *PromptProtectionRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromptProtectionRuleCreate) SetNillableUpdatedAt(v *time.Time) *PromptProtectionRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PromptProtectionRuleCreate) SetDeletedAt(v int) *PromptProtectionRuleCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PromptProtectionRuleCreate) SetNillableDeletedAt(v *int) *PromptProtectionRuleCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PromptProtectionRuleCreate) SetName(v string) *PromptProtectionRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PromptProtectionRuleCreate) SetDescription(v string) *PromptProtectionRuleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PromptProtectionRuleCreate) SetNillableDescription(v *string) *PromptProtectionRuleCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPattern sets the "pattern" field.
func (_c *PromptProtectionRuleCreate) SetPattern(v string) *PromptProtectionRuleCreate {
	_c.mutation.SetPattern(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PromptProtectionRuleCreate) SetStatus(v promptprotectionrule.Status) *PromptProtectionRuleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PromptProtectionRuleCreate) SetNillableStatus(v *promptprotectionrule.Status) *PromptProtectionRuleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSettings sets the "settings" field.
func (_c *PromptProtectionRuleCreate) SetSettings(v *objects.PromptProtectionSettings) *PromptProtectionRuleCreate {
	_c.mutation.SetSettings(v)
	return _c
}

// Mutation returns the PromptProtectionRuleMutation object of the builder.
func (_c *PromptProtectionRuleCreate) Mutation() *PromptProtectionRuleMutation {
	return _c.mutation
}

// Save creates the PromptProtectionRule in the database.
func (_c *PromptProtectionRuleCreate) Save(ctx context.Context) (*PromptProtectionRule, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromptProtectionRuleCreate) SaveX(ctx context.Context) *PromptProtectionRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptProtectionRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptProtectionRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromptProtectionRuleCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if promptprotectionrule.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized promptprotectionrule.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := promptprotectionrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if promptprotectionrule.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized promptprotectionrule.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := promptprotectionrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := promptprotectionrule.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := promptprotectionrule.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := promptprotectionrule.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromptProtectionRuleCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "PromptProtectionRule.deleted_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PromptProtectionRule.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "PromptProtectionRule.description"`)}
	}
	if _, ok := _c.mutation.Pattern(); !ok {
		return &ValidationError{Name: "pattern", err: errors.New(`ent: missing required field "PromptProtectionRule.pattern"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PromptProtectionRule.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := promptprotectionrule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PromptProtectionRule.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Settings(); !ok {
		return &ValidationError{Name: "settings", err: errors.New(`ent: missing required field "PromptProtectionRule.settings"`)}
	}
	return nil
}

func (_c *PromptProtectionRuleCreate) sqlSave(ctx context.Context) (*PromptProtectionRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromptProtectionRuleCreate) createSpec() (*PromptProtectionRule, *sqlgraph.CreateSpec) {
	var (
		_node = &PromptProtectionRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promptprotectionrule.Table, sqlgraph.NewFieldSpec(promptprotectionrule.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promptprotectionrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promptprotectionrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(promptprotectionrule.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(promptprotectionrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(promptprotectionrule.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Pattern(); ok {
		_spec.SetField(promptprotectionrule.FieldPattern, field.TypeString, value)
		_node.Pattern = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(promptprotectionrule.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Settings(); ok {
		_spec.SetField(promptprotectionrule.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromptProtectionRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromptProtectionRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromptProtectionRuleCreate) OnConflict(opts ...sql.ConflictOption) *PromptProtectionRuleUpsertOne {
	_c.conflict = opts
	return &PromptProtectionRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromptProtectionRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromptProtectionRuleCreate) OnConflictColumns(columns ...string) *PromptProtectionRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromptProtectionRuleUpsertOne{
		create: _c,
	}
}

type (
	// PromptProtectionRuleUpsertOne is the builder for "upsert"-ing
	//  one PromptProtectionRule node.
	PromptProtectionRuleUpsertOne struct {
		create *PromptProtectionRuleCreate
	}

	// PromptProtectionRuleUpsert is the "OnConflict" setter.
	PromptProtectionRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptProtectionRuleUpsert) SetUpdatedAt(v time.Time) *PromptProtectionRuleUpsert {
	u.Set(promptprotectionrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsert) UpdateUpdatedAt() *PromptProtectionRuleUpsert {
	u.SetExcluded(promptprotectionrule.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PromptProtectionRuleUpsert) SetDeletedAt(v int) *PromptProtectionRuleUpsert {
	u.Set(promptprotectionrule.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsert) UpdateDeletedAt() *PromptProtectionRuleUpsert {
	u.SetExcluded(promptprotectionrule.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *PromptProtectionRuleUpsert) AddDeletedAt(v int) *PromptProtectionRuleUpsert {
	u.Add(promptprotectionrule.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *PromptProtectionRuleUpsert) SetName(v string) *PromptProtectionRuleUpsert {
	u.Set(promptprotectionrule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsert) UpdateName() *PromptProtectionRuleUpsert {
	u.SetExcluded(promptprotectionrule.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *PromptProtectionRuleUpsert) SetDescription(v string) *PromptProtectionRuleUpsert {
	u.Set(promptprotectionrule.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsert) UpdateDescription() *PromptProtectionRuleUpsert {
	u.SetExcluded(promptprotectionrule.FieldDescription)
	return u
}

// SetPattern sets the "pattern" field.
func (u *PromptProtectionRuleUpsert) SetPattern(v string) *PromptProtectionRuleUpsert {
	u.Set(promptprotectionrule.FieldPattern, v)
	return u
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsert) UpdatePattern() *PromptProtectionRuleUpsert {
	u.SetExcluded(promptprotectionrule.FieldPattern)
	return u
}

// SetStatus sets the "status" field.
func (u *PromptProtectionRuleUpsert) SetStatus(v promptprotectionrule.Status) *PromptProtectionRuleUpsert {
	u.Set(promptprotectionrule.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsert) UpdateStatus() *PromptProtectionRuleUpsert {
	u.SetExcluded(promptprotectionrule.FieldStatus)
	return u
}

// SetSettings sets the "settings" field.
func (u *PromptProtectionRuleUpsert) SetSettings(v *objects.PromptProtectionSettings) *PromptProtectionRuleUpsert {
	u.Set(promptprotectionrule.FieldSettings, v)
	return u
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsert) UpdateSettings() *PromptProtectionRuleUpsert {
	u.SetExcluded(promptprotectionrule.FieldSettings)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PromptProtectionRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromptProtectionRuleUpsertOne) UpdateNewValues() *PromptProtectionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promptprotectionrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromptProtectionRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromptProtectionRuleUpsertOne) Ignore() *PromptProtectionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromptProtectionRuleUpsertOne) DoNothing() *PromptProtectionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromptProtectionRuleCreate.OnConflict
// documentation for more info.
func (u *PromptProtectionRuleUpsertOne) Update(set func(*PromptProtectionRuleUpsert)) *PromptProtectionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromptProtectionRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptProtectionRuleUpsertOne) SetUpdatedAt(v time.Time) *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertOne) UpdateUpdatedAt() *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PromptProtectionRuleUpsertOne) SetDeletedAt(v int) *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *PromptProtectionRuleUpsertOne) AddDeletedAt(v int) *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertOne) UpdateDeletedAt() *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *PromptProtectionRuleUpsertOne) SetName(v string) *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertOne) UpdateName() *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *PromptProtectionRuleUpsertOne) SetDescription(v string) *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertOne) UpdateDescription() *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateDescription()
	})
}

// SetPattern sets the "pattern" field.
func (u *PromptProtectionRuleUpsertOne) SetPattern(v string) *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertOne) UpdatePattern() *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdatePattern()
	})
}

// SetStatus sets the "status" field.
func (u *PromptProtectionRuleUpsertOne) SetStatus(v promptprotectionrule.Status) *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertOne) UpdateStatus() *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateStatus()
	})
}

// SetSettings sets the "settings" field.
func (u *PromptProtectionRuleUpsertOne) SetSettings(v *objects.PromptProtectionSettings) *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertOne) UpdateSettings() *PromptProtectionRuleUpsertOne {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateSettings()
	})
}

// Exec executes the query.
func (u *PromptProtectionRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromptProtectionRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromptProtectionRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromptProtectionRuleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromptProtectionRuleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromptProtectionRuleCreateBulk is the builder for creating many PromptProtectionRule entities in bulk.
type PromptProtectionRuleCreateBulk struct {
	config
	err      error
	builders []*PromptProtectionRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the PromptProtectionRule entities in the database.
func (_c *PromptProtectionRuleCreateBulk) Save(ctx context.Context) ([]*PromptProtectionRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromptProtectionRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromptProtectionRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromptProtectionRuleCreateBulk) SaveX(ctx context.Context) []*PromptProtectionRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptProtectionRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptProtectionRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromptProtectionRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromptProtectionRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromptProtectionRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromptProtectionRuleUpsertBulk {
	_c.conflict = opts
	return &PromptProtectionRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromptProtectionRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromptProtectionRuleCreateBulk) OnConflictColumns(columns ...string) *PromptProtectionRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromptProtectionRuleUpsertBulk{
		create: _c,
	}
}

// PromptProtectionRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of PromptProtectionRule nodes.
type PromptProtectionRuleUpsertBulk struct {
	create *PromptProtectionRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromptProtectionRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromptProtectionRuleUpsertBulk) UpdateNewValues() *PromptProtectionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promptprotectionrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromptProtectionRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromptProtectionRuleUpsertBulk) Ignore() *PromptProtectionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromptProtectionRuleUpsertBulk) DoNothing() *PromptProtectionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromptProtectionRuleCreateBulk.OnConflict
// documentation for more info.
func (u *PromptProtectionRuleUpsertBulk) Update(set func(*PromptProtectionRuleUpsert)) *PromptProtectionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromptProtectionRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptProtectionRuleUpsertBulk) SetUpdatedAt(v time.Time) *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertBulk) UpdateUpdatedAt() *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PromptProtectionRuleUpsertBulk) SetDeletedAt(v int) *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *PromptProtectionRuleUpsertBulk) AddDeletedAt(v int) *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertBulk) UpdateDeletedAt() *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *PromptProtectionRuleUpsertBulk) SetName(v string) *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertBulk) UpdateName() *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *PromptProtectionRuleUpsertBulk) SetDescription(v string) *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertBulk) UpdateDescription() *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateDescription()
	})
}

// SetPattern sets the "pattern" field.
func (u *PromptProtectionRuleUpsertBulk) SetPattern(v string) *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertBulk) UpdatePattern() *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdatePattern()
	})
}

// SetStatus sets the "status" field.
func (u *PromptProtectionRuleUpsertBulk) SetStatus(v promptprotectionrule.Status) *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertBulk) UpdateStatus() *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateStatus()
	})
}

// SetSettings sets the "settings" field.
func (u *PromptProtectionRuleUpsertBulk) SetSettings(v *objects.PromptProtectionSettings) *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *PromptProtectionRuleUpsertBulk) UpdateSettings() *PromptProtectionRuleUpsertBulk {
	return u.Update(func(s *PromptProtectionRuleUpsert) {
		s.UpdateSettings()
	})
}

// Exec executes the query.
func (u *PromptProtectionRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromptProtectionRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromptProtectionRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromptProtectionRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
