// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/providerquotastatus"
)

// ProviderQuotaStatus is the model entity for the ProviderQuotaStatus schema.
type ProviderQuotaStatus struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// ProviderType holds the value of the "provider_type" field.
	ProviderType providerquotastatus.ProviderType `json:"provider_type,omitempty"`
	// Overall status: available, warning, exhausted, unknown
	Status providerquotastatus.Status `json:"status,omitempty"`
	// Provider-specific quota data
	QuotaData map[string]interface{} `json:"quota_data,omitempty"`
	// Timestamp for next quota reset (primary window)
	NextResetAt *time.Time `json:"next_reset_at,omitempty"`
	// True if status is available or warning
	Ready bool `json:"ready,omitempty"`
	// Timestamp for next scheduled quota check
	NextCheckAt time.Time `json:"next_check_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProviderQuotaStatusQuery when eager-loading is set.
	Edges        ProviderQuotaStatusEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProviderQuotaStatusEdges holds the relations/edges for other nodes in the graph.
type ProviderQuotaStatusEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderQuotaStatusEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderQuotaStatus) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerquotastatus.FieldQuotaData:
			values[i] = new([]byte)
		case providerquotastatus.FieldReady:
			values[i] = new(sql.NullBool)
		case providerquotastatus.FieldID, providerquotastatus.FieldDeletedAt, providerquotastatus.FieldChannelID:
			values[i] = new(sql.NullInt64)
		case providerquotastatus.FieldProviderType, providerquotastatus.FieldStatus:
			values[i] = new(sql.NullString)
		case providerquotastatus.FieldCreatedAt, providerquotastatus.FieldUpdatedAt, providerquotastatus.FieldNextResetAt, providerquotastatus.FieldNextCheckAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderQuotaStatus fields.
func (_m *ProviderQuotaStatus) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerquotastatus.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case providerquotastatus.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case providerquotastatus.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case providerquotastatus.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case providerquotastatus.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case providerquotastatus.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = providerquotastatus.ProviderType(value.String)
			}
		case providerquotastatus.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = providerquotastatus.Status(value.String)
			}
		case providerquotastatus.FieldQuotaData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field quota_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.QuotaData); err != nil {
					return fmt.Errorf("unmarshal field quota_data: %w", err)
				}
			}
		case providerquotastatus.FieldNextResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_reset_at", values[i])
			} else if value.Valid {
				_m.NextResetAt = new(time.Time)
				*_m.NextResetAt = value.Time
			}
		case providerquotastatus.FieldReady:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field ready", values[i])
			} else if value.Valid {
				_m.Ready = value.Bool
			}
		case providerquotastatus.FieldNextCheckAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_check_at", values[i])
			} else if value.Valid {
				_m.NextCheckAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderQuotaStatus.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderQuotaStatus) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the ProviderQuotaStatus entity.
func (_m *ProviderQuotaStatus) QueryChannel() *ChannelQuery {
	return NewProviderQuotaStatusClient(_m.config).QueryChannel(_m)
}

// Update returns a builder for updating this ProviderQuotaStatus.
// Note that you need to call ProviderQuotaStatus.Unwrap() before calling this method if this ProviderQuotaStatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderQuotaStatus) Update() *ProviderQuotaStatusUpdateOne {
	return NewProviderQuotaStatusClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderQuotaStatus entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderQuotaStatus) Unwrap() *ProviderQuotaStatus {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderQuotaStatus is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderQuotaStatus) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderQuotaStatus(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("quota_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaData))
	builder.WriteString(", ")
	if v := _m.NextResetAt; v != nil {
		builder.WriteString("next_reset_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("ready=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ready))
	builder.WriteString(", ")
	builder.WriteString("next_check_at=")
	builder.WriteString(_m.NextCheckAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderQuotaStatusSlice is a parsable slice of ProviderQuotaStatus.
type ProviderQuotaStatusSlice []*ProviderQuotaStatus
