// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/datastorage"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/trace"
	"github.com/looplj/axonhub/internal/objects"
)

// Request is the model entity for the Request schema.
type Request struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// API Key ID of the request, null for the request from the Admin.
	APIKeyID int `json:"api_key_id,omitempty"`
	// Project ID, default to 1 for backward compatibility
	ProjectID int `json:"project_id,omitempty"`
	// Trace ID that this request belongs to
	TraceID int `json:"trace_id,omitempty"`
	// Data Storage ID that this request belongs to
	DataStorageID int `json:"data_storage_id,omitempty"`
	// Source holds the value of the "source" field.
	Source request.Source `json:"source,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// Format holds the value of the "format" field.
	Format string `json:"format,omitempty"`
	// Request headers
	RequestHeaders objects.JSONRawMessage `json:"request_headers,omitempty"`
	// RequestBody holds the value of the "request_body" field.
	RequestBody objects.JSONRawMessage `json:"request_body,omitempty"`
	// ResponseBody holds the value of the "response_body" field.
	ResponseBody objects.JSONRawMessage `json:"response_body,omitempty"`
	// ResponseChunks holds the value of the "response_chunks" field.
	ResponseChunks []objects.JSONRawMessage `json:"response_chunks,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID string `json:"external_id,omitempty"`
	// Status holds the value of the "status" field.
	Status request.Status `json:"status,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// ClientIP holds the value of the "client_ip" field.
	ClientIP string `json:"client_ip,omitempty"`
	// MetricsLatencyMs holds the value of the "metrics_latency_ms" field.
	MetricsLatencyMs *int64 `json:"metrics_latency_ms,omitempty"`
	// MetricsFirstTokenLatencyMs holds the value of the "metrics_first_token_latency_ms" field.
	MetricsFirstTokenLatencyMs *int64 `json:"metrics_first_token_latency_ms,omitempty"`
	// whether the generated content has been saved to external storage
	ContentSaved bool `json:"content_saved,omitempty"`
	// data storage id used to save the content file
	ContentStorageID *int `json:"content_storage_id,omitempty"`
	// storage key/path of the saved content file
	ContentStorageKey *string `json:"content_storage_key,omitempty"`
	// when the content file was saved
	ContentSavedAt *time.Time `json:"content_saved_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RequestQuery when eager-loading is set.
	Edges        RequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RequestEdges holds the relations/edges for other nodes in the graph.
type RequestEdges struct {
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Trace holds the value of the trace edge.
	Trace *Trace `json:"trace,omitempty"`
	// DataStorage holds the value of the data_storage edge.
	DataStorage *DataStorage `json:"data_storage,omitempty"`
	// Executions holds the value of the executions edge.
	Executions []*RequestExecution `json:"executions,omitempty"`
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
	// totalCount holds the count of the edges above.
	totalCount [7]map[string]int

	namedExecutions map[string][]*RequestExecution
	namedUsageLogs  map[string][]*UsageLog
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// TraceOrErr returns the Trace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestEdges) TraceOrErr() (*Trace, error) {
	if e.Trace != nil {
		return e.Trace, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: trace.Label}
	}
	return nil, &NotLoadedError{edge: "trace"}
}

// DataStorageOrErr returns the DataStorage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestEdges) DataStorageOrErr() (*DataStorage, error) {
	if e.DataStorage != nil {
		return e.DataStorage, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: datastorage.Label}
	}
	return nil, &NotLoadedError{edge: "data_storage"}
}

// ExecutionsOrErr returns the Executions value or an error if the edge
// was not loaded in eager-loading.
func (e RequestEdges) ExecutionsOrErr() ([]*RequestExecution, error) {
	if e.loadedTypes[4] {
		return e.Executions, nil
	}
	return nil, &NotLoadedError{edge: "executions"}
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e RequestEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[6] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Request) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case request.FieldRequestHeaders, request.FieldRequestBody, request.FieldResponseBody, request.FieldResponseChunks:
			values[i] = new([]byte)
		case request.FieldStream, request.FieldContentSaved:
			values[i] = new(sql.NullBool)
		case request.FieldID, request.FieldAPIKeyID, request.FieldProjectID, request.FieldTraceID, request.FieldDataStorageID, request.FieldChannelID, request.FieldMetricsLatencyMs, request.FieldMetricsFirstTokenLatencyMs, request.FieldContentStorageID:
			values[i] = new(sql.NullInt64)
		case request.FieldSource, request.FieldModelID, request.FieldFormat, request.FieldExternalID, request.FieldStatus, request.FieldClientIP, request.FieldContentStorageKey:
			values[i] = new(sql.NullString)
		case request.FieldCreatedAt, request.FieldUpdatedAt, request.FieldContentSavedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Request fields.
func (_m *Request) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case request.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case request.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case request.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case request.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = int(value.Int64)
			}
		case request.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case request.FieldTraceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trace_id", values[i])
			} else if value.Valid {
				_m.TraceID = int(value.Int64)
			}
		case request.FieldDataStorageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field data_storage_id", values[i])
			} else if value.Valid {
				_m.DataStorageID = int(value.Int64)
			}
		case request.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = request.Source(value.String)
			}
		case request.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case request.FieldFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field format", values[i])
			} else if value.Valid {
				_m.Format = value.String
			}
		case request.FieldRequestHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestHeaders); err != nil {
					return fmt.Errorf("unmarshal field request_headers: %w", err)
				}
			}
		case request.FieldRequestBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestBody); err != nil {
					return fmt.Errorf("unmarshal field request_body: %w", err)
				}
			}
		case request.FieldResponseBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponseBody); err != nil {
					return fmt.Errorf("unmarshal field response_body: %w", err)
				}
			}
		case request.FieldResponseChunks:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_chunks", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponseChunks); err != nil {
					return fmt.Errorf("unmarshal field response_chunks: %w", err)
				}
			}
		case request.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case request.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = value.String
			}
		case request.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = request.Status(value.String)
			}
		case request.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				_m.Stream = value.Bool
			}
		case request.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = value.String
			}
		case request.FieldMetricsLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metrics_latency_ms", values[i])
			} else if value.Valid {
				_m.MetricsLatencyMs = new(int64)
				*_m.MetricsLatencyMs = value.Int64
			}
		case request.FieldMetricsFirstTokenLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metrics_first_token_latency_ms", values[i])
			} else if value.Valid {
				_m.MetricsFirstTokenLatencyMs = new(int64)
				*_m.MetricsFirstTokenLatencyMs = value.Int64
			}
		case request.FieldContentSaved:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field content_saved", values[i])
			} else if value.Valid {
				_m.ContentSaved = value.Bool
			}
		case request.FieldContentStorageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field content_storage_id", values[i])
			} else if value.Valid {
				_m.ContentStorageID = new(int)
				*_m.ContentStorageID = int(value.Int64)
			}
		case request.FieldContentStorageKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_storage_key", values[i])
			} else if value.Valid {
				_m.ContentStorageKey = new(string)
				*_m.ContentStorageKey = value.String
			}
		case request.FieldContentSavedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field content_saved_at", values[i])
			} else if value.Valid {
				_m.ContentSavedAt = new(time.Time)
				*_m.ContentSavedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Request.
// This includes values selected through modifiers, order, etc.
func (_m *Request) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKey queries the "api_key" edge of the Request entity.
func (_m *Request) QueryAPIKey() *APIKeyQuery {
	return NewRequestClient(_m.config).QueryAPIKey(_m)
}

// QueryProject queries the "project" edge of the Request entity.
func (_m *Request) QueryProject() *ProjectQuery {
	return NewRequestClient(_m.config).QueryProject(_m)
}

// QueryTrace queries the "trace" edge of the Request entity.
func (_m *Request) QueryTrace() *TraceQuery {
	return NewRequestClient(_m.config).QueryTrace(_m)
}

// QueryDataStorage queries the "data_storage" edge of the Request entity.
func (_m *Request) QueryDataStorage() *DataStorageQuery {
	return NewRequestClient(_m.config).QueryDataStorage(_m)
}

// QueryExecutions queries the "executions" edge of the Request entity.
func (_m *Request) QueryExecutions() *RequestExecutionQuery {
	return NewRequestClient(_m.config).QueryExecutions(_m)
}

// QueryChannel queries the "channel" edge of the Request entity.
func (_m *Request) QueryChannel() *ChannelQuery {
	return NewRequestClient(_m.config).QueryChannel(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the Request entity.
func (_m *Request) QueryUsageLogs() *UsageLogQuery {
	return NewRequestClient(_m.config).QueryUsageLogs(_m)
}

// Update returns a builder for updating this Request.
// Note that you need to call Request.Unwrap() before calling this method if this Request
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Request) Update() *RequestUpdateOne {
	return NewRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Request entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Request) Unwrap() *Request {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Request is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Request) String() string {
	var builder strings.Builder
	builder.WriteString("Request(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("trace_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TraceID))
	builder.WriteString(", ")
	builder.WriteString("data_storage_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DataStorageID))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("format=")
	builder.WriteString(_m.Format)
	builder.WriteString(", ")
	builder.WriteString("request_headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestHeaders))
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBody))
	builder.WriteString(", ")
	builder.WriteString("response_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBody))
	builder.WriteString(", ")
	builder.WriteString("response_chunks=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseChunks))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("external_id=")
	builder.WriteString(_m.ExternalID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stream))
	builder.WriteString(", ")
	builder.WriteString("client_ip=")
	builder.WriteString(_m.ClientIP)
	builder.WriteString(", ")
	if v := _m.MetricsLatencyMs; v != nil {
		builder.WriteString("metrics_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MetricsFirstTokenLatencyMs; v != nil {
		builder.WriteString("metrics_first_token_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("content_saved=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContentSaved))
	builder.WriteString(", ")
	if v := _m.ContentStorageID; v != nil {
		builder.WriteString("content_storage_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ContentStorageKey; v != nil {
		builder.WriteString("content_storage_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContentSavedAt; v != nil {
		builder.WriteString("content_saved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedExecutions returns the Executions named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Request) NamedExecutions(name string) ([]*RequestExecution, error) {
	if _m.Edges.namedExecutions == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedExecutions[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Request) appendNamedExecutions(name string, edges ...*RequestExecution) {
	if _m.Edges.namedExecutions == nil {
		_m.Edges.namedExecutions = make(map[string][]*RequestExecution)
	}
	if len(edges) == 0 {
		_m.Edges.namedExecutions[name] = []*RequestExecution{}
	} else {
		_m.Edges.namedExecutions[name] = append(_m.Edges.namedExecutions[name], edges...)
	}
}

// NamedUsageLogs returns the UsageLogs named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Request) NamedUsageLogs(name string) ([]*UsageLog, error) {
	if _m.Edges.namedUsageLogs == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedUsageLogs[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Request) appendNamedUsageLogs(name string, edges ...*UsageLog) {
	if _m.Edges.namedUsageLogs == nil {
		_m.Edges.namedUsageLogs = make(map[string][]*UsageLog)
	}
	if len(edges) == 0 {
		_m.Edges.namedUsageLogs[name] = []*UsageLog{}
	} else {
		_m.Edges.namedUsageLogs[name] = append(_m.Edges.namedUsageLogs[name], edges...)
	}
}

// Requests is a parsable slice of Request.
type Requests []*Request
