version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "npm"
    directories:
      - "/web/classic"
      - "/web/default"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
