// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package openapi

type APIKey struct {
	Key    string   `json:"key"`
	Name   string   `json:"name"`
	Scopes []string `json:"scopes,omitempty"`
}

type Mutation struct {
}
