package openapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/contexts"
)

// CreateLLMAPIKey is the resolver for the createLLMAPIKey field.
func (r *mutationResolver) CreateLLMAPIKey(ctx context.Context, name string) (*APIKey, error) {
	ownerKey, ok := contexts.GetAPIKey(ctx)
	if !ok || ownerKey == nil {
		return nil, fmt.Errorf("api key not found in context")
	}

	apiKey, err := r.apiKeyService.CreateLLMAPIKey(ctx, ownerKey, name)
	if err != nil {
		return nil, err
	}

	return &APIKey{
		Key:    apiKey.Key,
		Name:   apiKey.Name,
		Scopes: apiKey.Scopes,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
