// Code generated by ent, DO NOT EDIT.

package usagelog

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/objects"
)

const (
	// Label holds the string label denoting the usagelog type in the database.
	Label = "usage_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldPromptTokens holds the string denoting the prompt_tokens field in the database.
	FieldPromptTokens = "prompt_tokens"
	// FieldCompletionTokens holds the string denoting the completion_tokens field in the database.
	FieldCompletionTokens = "completion_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldPromptAudioTokens holds the string denoting the prompt_audio_tokens field in the database.
	FieldPromptAudioTokens = "prompt_audio_tokens"
	// FieldPromptCachedTokens holds the string denoting the prompt_cached_tokens field in the database.
	FieldPromptCachedTokens = "prompt_cached_tokens"
	// FieldPromptWriteCachedTokens holds the string denoting the prompt_write_cached_tokens field in the database.
	FieldPromptWriteCachedTokens = "prompt_write_cached_tokens"
	// FieldPromptWriteCachedTokens5m holds the string denoting the prompt_write_cached_tokens_5m field in the database.
	FieldPromptWriteCachedTokens5m = "prompt_write_cached_tokens_5m"
	// FieldPromptWriteCachedTokens1h holds the string denoting the prompt_write_cached_tokens_1h field in the database.
	FieldPromptWriteCachedTokens1h = "prompt_write_cached_tokens_1h"
	// FieldCompletionAudioTokens holds the string denoting the completion_audio_tokens field in the database.
	FieldCompletionAudioTokens = "completion_audio_tokens"
	// FieldCompletionReasoningTokens holds the string denoting the completion_reasoning_tokens field in the database.
	FieldCompletionReasoningTokens = "completion_reasoning_tokens"
	// FieldCompletionAcceptedPredictionTokens holds the string denoting the completion_accepted_prediction_tokens field in the database.
	FieldCompletionAcceptedPredictionTokens = "completion_accepted_prediction_tokens"
	// FieldCompletionRejectedPredictionTokens holds the string denoting the completion_rejected_prediction_tokens field in the database.
	FieldCompletionRejectedPredictionTokens = "completion_rejected_prediction_tokens"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldFormat holds the string denoting the format field in the database.
	FieldFormat = "format"
	// FieldTotalCost holds the string denoting the total_cost field in the database.
	FieldTotalCost = "total_cost"
	// FieldCostItems holds the string denoting the cost_items field in the database.
	FieldCostItems = "cost_items"
	// FieldCostPriceReferenceID holds the string denoting the cost_price_reference_id field in the database.
	FieldCostPriceReferenceID = "cost_price_reference_id"
	// EdgeRequest holds the string denoting the request edge name in mutations.
	EdgeRequest = "request"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// Table holds the table name of the usagelog in the database.
	Table = "usage_logs"
	// RequestTable is the table that holds the request relation/edge.
	RequestTable = "usage_logs"
	// RequestInverseTable is the table name for the Request entity.
	// It exists in this package in order to avoid circular dependency with the "request" package.
	RequestInverseTable = "requests"
	// RequestColumn is the table column denoting the request relation/edge.
	RequestColumn = "request_id"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "usage_logs"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "usage_logs"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
)

// Columns holds all SQL columns for usagelog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRequestID,
	FieldAPIKeyID,
	FieldProjectID,
	FieldChannelID,
	FieldModelID,
	FieldPromptTokens,
	FieldCompletionTokens,
	FieldTotalTokens,
	FieldPromptAudioTokens,
	FieldPromptCachedTokens,
	FieldPromptWriteCachedTokens,
	FieldPromptWriteCachedTokens5m,
	FieldPromptWriteCachedTokens1h,
	FieldCompletionAudioTokens,
	FieldCompletionReasoningTokens,
	FieldCompletionAcceptedPredictionTokens,
	FieldCompletionRejectedPredictionTokens,
	FieldSource,
	FieldFormat,
	FieldTotalCost,
	FieldCostItems,
	FieldCostPriceReferenceID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultProjectID holds the default value on creation for the "project_id" field.
	DefaultProjectID int
	// DefaultPromptTokens holds the default value on creation for the "prompt_tokens" field.
	DefaultPromptTokens int64
	// DefaultCompletionTokens holds the default value on creation for the "completion_tokens" field.
	DefaultCompletionTokens int64
	// DefaultTotalTokens holds the default value on creation for the "total_tokens" field.
	DefaultTotalTokens int64
	// DefaultPromptAudioTokens holds the default value on creation for the "prompt_audio_tokens" field.
	DefaultPromptAudioTokens int64
	// DefaultPromptCachedTokens holds the default value on creation for the "prompt_cached_tokens" field.
	DefaultPromptCachedTokens int64
	// DefaultPromptWriteCachedTokens holds the default value on creation for the "prompt_write_cached_tokens" field.
	DefaultPromptWriteCachedTokens int64
	// DefaultPromptWriteCachedTokens5m holds the default value on creation for the "prompt_write_cached_tokens_5m" field.
	DefaultPromptWriteCachedTokens5m int64
	// DefaultPromptWriteCachedTokens1h holds the default value on creation for the "prompt_write_cached_tokens_1h" field.
	DefaultPromptWriteCachedTokens1h int64
	// DefaultCompletionAudioTokens holds the default value on creation for the "completion_audio_tokens" field.
	DefaultCompletionAudioTokens int64
	// DefaultCompletionReasoningTokens holds the default value on creation for the "completion_reasoning_tokens" field.
	DefaultCompletionReasoningTokens int64
	// DefaultCompletionAcceptedPredictionTokens holds the default value on creation for the "completion_accepted_prediction_tokens" field.
	DefaultCompletionAcceptedPredictionTokens int64
	// DefaultCompletionRejectedPredictionTokens holds the default value on creation for the "completion_rejected_prediction_tokens" field.
	DefaultCompletionRejectedPredictionTokens int64
	// DefaultFormat holds the default value on creation for the "format" field.
	DefaultFormat string
	// DefaultCostItems holds the default value on creation for the "cost_items" field.
	DefaultCostItems []objects.CostItem
)

// Source defines the type for the "source" enum field.
type Source string

// SourceAPI is the default value of the Source enum.
const DefaultSource = SourceAPI

// Source values.
const (
	SourceAPI        Source = "api"
	SourcePlayground Source = "playground"
	SourceTest       Source = "test"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceAPI, SourcePlayground, SourceTest:
		return nil
	default:
		return fmt.Errorf("usagelog: invalid enum value for source field: %q", s)
	}
}

// OrderOption defines the ordering options for the UsageLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByPromptTokens orders the results by the prompt_tokens field.
func ByPromptTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptTokens, opts...).ToFunc()
}

// ByCompletionTokens orders the results by the completion_tokens field.
func ByCompletionTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByPromptAudioTokens orders the results by the prompt_audio_tokens field.
func ByPromptAudioTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptAudioTokens, opts...).ToFunc()
}

// ByPromptCachedTokens orders the results by the prompt_cached_tokens field.
func ByPromptCachedTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptCachedTokens, opts...).ToFunc()
}

// ByPromptWriteCachedTokens orders the results by the prompt_write_cached_tokens field.
func ByPromptWriteCachedTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptWriteCachedTokens, opts...).ToFunc()
}

// ByPromptWriteCachedTokens5m orders the results by the prompt_write_cached_tokens_5m field.
func ByPromptWriteCachedTokens5m(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptWriteCachedTokens5m, opts...).ToFunc()
}

// ByPromptWriteCachedTokens1h orders the results by the prompt_write_cached_tokens_1h field.
func ByPromptWriteCachedTokens1h(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptWriteCachedTokens1h, opts...).ToFunc()
}

// ByCompletionAudioTokens orders the results by the completion_audio_tokens field.
func ByCompletionAudioTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionAudioTokens, opts...).ToFunc()
}

// ByCompletionReasoningTokens orders the results by the completion_reasoning_tokens field.
func ByCompletionReasoningTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionReasoningTokens, opts...).ToFunc()
}

// ByCompletionAcceptedPredictionTokens orders the results by the completion_accepted_prediction_tokens field.
func ByCompletionAcceptedPredictionTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionAcceptedPredictionTokens, opts...).ToFunc()
}

// ByCompletionRejectedPredictionTokens orders the results by the completion_rejected_prediction_tokens field.
func ByCompletionRejectedPredictionTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionRejectedPredictionTokens, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByFormat orders the results by the format field.
func ByFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormat, opts...).ToFunc()
}

// ByTotalCost orders the results by the total_cost field.
func ByTotalCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCost, opts...).ToFunc()
}

// ByCostPriceReferenceID orders the results by the cost_price_reference_id field.
func ByCostPriceReferenceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostPriceReferenceID, opts...).ToFunc()
}

// ByRequestField orders the results by request field.
func ByRequestField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestStep(), sql.OrderByField(field, opts...))
	}
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}
func newRequestStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RequestTable, RequestColumn),
	)
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Source) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Source) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Source(str)
	if err := SourceValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Source", str)
	}
	return nil
}
